'use client';

import { GlobalOutlined, PlusOutlined } from '@ant-design/icons';
import { Button, Card, Form, Input, InputNumber, Modal, Space, Switch, Table, Tag, Tooltip, Typography, message } from 'antd';
import { useMemo, useState } from 'react';

import { AdminEntityRowActions } from '@/components/admin/admin-row-actions';
import { adminTableFixedActionsColumn } from '@/components/admin/admin-table';
import { CommercePageHeader } from '@/components/commerce/commerce-page-header';
import { CommerceSettingsForm } from '@/components/commerce/commerce-settings-form';
import type { CommerceSettingsFormValues } from '@/components/commerce/commerce-settings-form';
import { ShippingCountryRatesModal } from '@/components/commerce/shipping-country-rates-modal';
import { createLocalId, ratesForShippingMethod } from '@/components/commerce/commerce-utils';
import { useCommerceConfig } from '@/components/commerce/use-commerce-config';
import { ADMIN_ACTION_TOOLTIP_PROPS } from '@/components/admin/admin-row-actions';
import { buildAdminListRowIndexColumn } from '@/lib/admin-list-query';
import type { CommerceConfig, ShippingMethodConfig } from '@/lib/commerce-config';
import { getShippingRateChipLabel } from '@/lib/commerce-shipping-rate';
import { resolveSlugForSave } from '@/lib/slug';

function resolveShippingMethodCodeForSave(
  values: ShippingMethodFormValues,
  methods: ShippingMethodConfig[],
  editingId: string | null,
) {
  const wasAutoGenerated = !values.code.trim();
  const baseCode = resolveSlugForSave({ sourceText: values.name, slug: values.code });
  if (!baseCode) {
    return { ok: false as const, message: '请填写编码，或填写名称以自动生成编码' };
  }

  const usedCodes = new Set(
    methods.filter((method) => method.id !== editingId).map((method) => method.code),
  );

  if (!usedCodes.has(baseCode)) {
    return { ok: true as const, code: baseCode, wasAutoGenerated };
  }

  if (!wasAutoGenerated) {
    return { ok: false as const, message: '编码已存在，请使用其他编码' };
  }

  let suffix = 2;
  let candidate = `${baseCode}-${suffix}`;
  while (usedCodes.has(candidate)) {
    suffix += 1;
    candidate = `${baseCode}-${suffix}`;
  }

  return { ok: true as const, code: candidate, wasAutoGenerated };
}

type ShippingMethodFormValues = {
  code: string;
  name: string;
  etaLabel: string;
  note: string;
  enabled: boolean;
};

export function ShippingMethodsClient({ initialConfig }: { initialConfig: CommerceConfig }) {
  const { config, isPending, updateConfig, persistConfig } = useCommerceConfig(initialConfig);
  const [shippingMethodModalOpen, setShippingMethodModalOpen] = useState(false);
  const [ratesModalOpen, setRatesModalOpen] = useState(false);
  const [editingShippingMethodId, setEditingShippingMethodId] = useState<string | null>(null);
  const [editingMethod, setEditingMethod] = useState<ShippingMethodConfig | null>(null);
  const [initialRateId, setInitialRateId] = useState<string | null>(null);
  const [shippingMethodForm] = Form.useForm<ShippingMethodFormValues>();

  const sortedMethods = useMemo(
    () => [...config.shippingMethods].sort((left, right) => left.sortOrder - right.sortOrder || left.name.localeCompare(right.name)),
    [config.shippingMethods],
  );

  function handleSettingsChange(changedValues: Partial<CommerceSettingsFormValues>) {
    updateConfig((current) => ({
      ...current,
      currencyCode: changedValues.currencyCode ?? current.currencyCode,
      defaultCountryCode: changedValues.defaultCountryCode ?? current.defaultCountryCode,
      defaultShippingMethodCode: changedValues.defaultShippingMethodCode ?? current.defaultShippingMethodCode,
    }));
  }

  function openShippingMethodModal(method?: ShippingMethodConfig) {
    setEditingShippingMethodId(method?.id ?? null);
    shippingMethodForm.setFieldsValue({
      code: method?.code ?? '',
      name: method?.name ?? '',
      etaLabel: method?.etaLabel ?? '',
      note: method?.note ?? '',
      enabled: method?.enabled ?? false,
    });
    setShippingMethodModalOpen(true);
  }

  function openRatesModal(method: ShippingMethodConfig, rateId?: string) {
    setEditingMethod(method);
    setInitialRateId(rateId ?? null);
    setRatesModalOpen(true);
  }

  function closeRatesModal() {
    setRatesModalOpen(false);
    setEditingMethod(null);
    setInitialRateId(null);
  }

  function patchMethodEnabled(row: ShippingMethodConfig, enabled: boolean) {
    updateConfig((current) => ({
      ...current,
      shippingMethods: current.shippingMethods.map((method) => (method.id === row.id ? { ...method, enabled } : method)),
    }));
  }

  function patchMethodSortOrder(id: string, sortOrder: number | null) {
    if (sortOrder == null) return;
    updateConfig((current) => ({
      ...current,
      shippingMethods: current.shippingMethods.map((method) => (method.id === id ? { ...method, sortOrder } : method)),
    }));
  }

  function saveShippingMethod() {
    void shippingMethodForm.validateFields(['name', 'enabled']).then(() => {
      const values = shippingMethodForm.getFieldsValue();
      const resolved = resolveShippingMethodCodeForSave(
        values,
        config.shippingMethods,
        editingShippingMethodId,
      );
      if (!resolved.ok) {
        void message.error(resolved.message);
        return;
      }

      shippingMethodForm.setFieldValue('code', resolved.code);

      void shippingMethodForm.validateFields(['code']).then(() => {
        const resolvedCode = resolved.code;

        updateConfig((current) => {
          const existing = editingShippingMethodId
            ? current.shippingMethods.find((method) => method.id === editingShippingMethodId)
            : null;
          const previousCode = existing?.code;
          const nextSortOrder = existing?.sortOrder
            ?? Math.max(-1, ...current.shippingMethods.map((method) => method.sortOrder)) + 1;
          const nextMethod: ShippingMethodConfig = {
            id: editingShippingMethodId ?? createLocalId('method'),
            code: resolvedCode,
            name: values.name.trim(),
            etaLabel: values.etaLabel?.trim() ?? '',
            note: values.note?.trim() ?? '',
            enabled: values.enabled,
            sortOrder: nextSortOrder,
          };

          const codeChanged = Boolean(previousCode && previousCode !== resolvedCode);

          return {
            ...current,
            defaultShippingMethodCode: codeChanged && current.defaultShippingMethodCode === previousCode
              ? resolvedCode
              : current.defaultShippingMethodCode,
            shippingMethods: editingShippingMethodId
              ? current.shippingMethods.map((method) => (method.id === editingShippingMethodId ? nextMethod : method))
              : [...current.shippingMethods, nextMethod],
            shippingCountryRates: codeChanged
              ? current.shippingCountryRates.map((rate) => (
                rate.shippingMethodCode === previousCode
                  ? { ...rate, shippingMethodCode: resolvedCode }
                  : rate
              ))
              : current.shippingCountryRates,
          };
        });
        setShippingMethodModalOpen(false);
        setEditingShippingMethodId(null);
        shippingMethodForm.resetFields();
        void message.success('保存成功');
      });
    });
  }

  function deleteShippingMethod(id: string) {
    if (config.shippingMethods.length <= 1) {
      void message.warning('至少保留一个物流方式');
      return;
    }

    updateConfig((current) => {
      const target = current.shippingMethods.find((method) => method.id === id);
      const nextShippingMethods = current.shippingMethods.filter((method) => method.id !== id);
      const fallbackMethodCode = nextShippingMethods[0]?.code ?? current.defaultShippingMethodCode;

      return {
        ...current,
        defaultShippingMethodCode: target?.code === current.defaultShippingMethodCode ? fallbackMethodCode : current.defaultShippingMethodCode,
        shippingMethods: nextShippingMethods,
        shippingCountryRates: target
          ? current.shippingCountryRates.filter((rate) => rate.shippingMethodCode !== target.code)
          : current.shippingCountryRates,
      };
    });
  }

  return (
    <Space orientation="vertical" size="large" style={{ width: '100%' }}>
      <CommercePageHeader
        title="物流方式"
        description="维护国际物流方式及各国运费与税率估算。购物车、Checkout 和支持页都会读取这里的配置。"
        statusMessage={null}
        isPending={isPending}
        onSave={persistConfig}
      />

      <CommerceSettingsForm config={config} onChange={handleSettingsChange} />

      <Card
        title="国际物流方式"
        extra={(
          <Button type="primary" icon={<PlusOutlined />} onClick={() => openShippingMethodModal()}>
            新增物流方式
          </Button>
        )}
      >
        <Table
          rowKey="id"
          pagination={false}
          scroll={{ x: 1180 }}
          dataSource={sortedMethods}
          columns={[
            buildAdminListRowIndexColumn(1, sortedMethods.length || 1),
            { title: '名称', dataIndex: 'name', width: 160 },
            { title: '编码', dataIndex: 'code', width: 140 },
            { title: '时效', dataIndex: 'etaLabel', width: 120 },
            {
              title: '排序',
              dataIndex: 'sortOrder',
              width: 96,
              render: (value: number, row: ShippingMethodConfig) => (
                <InputNumber
                  min={0}
                  precision={0}
                  value={value}
                  style={{ width: '100%' }}
                  onClick={(event) => event.stopPropagation()}
                  onChange={(next) => patchMethodSortOrder(row.id, next)}
                />
              ),
            },
            {
              title: '状态',
              dataIndex: 'enabled',
              width: 88,
              render: (value: boolean) => <Tag color={value ? 'green' : 'default'}>{value ? '启用' : '停用'}</Tag>,
            },
            { title: '说明', dataIndex: 'note', ellipsis: true },
            {
              title: '国家费率',
              key: 'countryRates',
              width: 220,
              render: (_: unknown, row: ShippingMethodConfig) => {
                const rates = ratesForShippingMethod(config, row.code);
                return (
                  <div className="shipping-method-country-rates">
                    <Tooltip title="编辑国家费率" {...ADMIN_ACTION_TOOLTIP_PROPS}>
                      <button
                        type="button"
                        className="admin-count-hotzone shipping-method-country-rates__toolbar"
                        aria-label="编辑国家费率"
                        onClick={() => openRatesModal(row)}
                      >
                        <span className="admin-count-hotzone__icon"><GlobalOutlined /></span>
                        <span className="admin-count-hotzone__count">({rates.length})</span>
                      </button>
                    </Tooltip>
                    {rates.length ? (
                      <div className="shipping-method-country-rates__list">
                        {rates.map((rate) => (
                          <button
                            key={rate.id}
                            type="button"
                            className="shipping-method-country-rates__chip"
                            onClick={() => openRatesModal(row, rate.id)}
                          >
                            {getShippingRateChipLabel(rate)}
                          </button>
                        ))}
                      </div>
                    ) : (
                      <Typography.Text type="secondary" className="shipping-method-country-rates__empty">
                        暂无费率
                      </Typography.Text>
                    )}
                  </div>
                );
              },
            },
            adminTableFixedActionsColumn({
              title: '操作',
              key: 'actions',
              render: (_: unknown, row: ShippingMethodConfig) => (
                <AdminEntityRowActions
                  isActive={row.enabled}
                  entityName="物流方式"
                  toggleDisableDescription="停用后前台将不再展示该物流方式。"
                  toggleEnableDescription="启用后物流方式将恢复展示。"
                  onEdit={() => openShippingMethodModal(row)}
                  onToggleActive={() => patchMethodEnabled(row, !row.enabled)}
                  onDelete={() => deleteShippingMethod(row.id)}
                />
              ),
            }),
          ]}
        />
      </Card>

      <Modal
        open={shippingMethodModalOpen}
        title={editingShippingMethodId ? '编辑物流方式' : '新增物流方式'}
        onCancel={() => {
          setShippingMethodModalOpen(false);
          setEditingShippingMethodId(null);
        }}
        onOk={saveShippingMethod}
        destroyOnHidden
      >
        <Form form={shippingMethodForm} layout="vertical" initialValues={{ enabled: false }}>
          <Form.Item label="名称" name="name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item
            label="编码"
            name="code"
            rules={[
              { required: true, message: '请填写编码' },
              {
                validator: async (_, value) => {
                  const trimmed = (value as string | undefined)?.trim();
                  if (!trimmed) return;
                  const normalized = resolveSlugForSave({ sourceText: '', slug: trimmed });
                  if (!normalized) {
                    throw new Error('编码仅支持小写英文、数字和横线');
                  }
                },
              },
            ]}
            extra="留空保存时将根据名称自动生成；物流方式内编码不可重复"
          >
            <Input placeholder="dhl-express" />
          </Form.Item>
          <Form.Item label="时效说明" name="etaLabel">
            <Input placeholder="2-5 个工作日" />
          </Form.Item>
          <Form.Item label="说明" name="note">
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item label="启用" name="enabled" valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>

      <ShippingCountryRatesModal
        open={ratesModalOpen}
        method={editingMethod}
        config={config}
        initialRateId={initialRateId}
        onClose={closeRatesModal}
        onChange={updateConfig}
      />
    </Space>
  );
}
